homepage:
  path: /
  defaults: {_controller: AppBundle:Default:index}

login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

logout:
  path: /logout
  defaults: {_controller: AppBundle:Security:logout}

admin:
  path: /admin
  defaults: {_controller: AppBundle:Default:admin}