AppBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
        username:
            type: string
            nullable: false
            length: 50
            fixed: false
        password:
            type: string
            nullable: false
            length: 100
            fixed: false
        ctime:
            type: datetime
            nullable: true
        roles:
            type: string
            nullable: false
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
